### ISSUE TITLE
Add additional "engagement" logic for utility mobile sidebar (content 5)

### ISSUE THREAD

**Issue by bniolet1** [mozilla/all-aboard#146]
We don't necessarily want or need a user to click on the mobile app store links since they'll be on desktop. The real idea is to 1) create a strong impression that the browser is available on mobile or 2) have them send a link to their device (see #141 )

This is the last stop on the journey and we don't want to close off the sticker to someone who didn't click a link but still got what we wanted them to from the content. So we need additional logic for this step to register engagement. Time with the sidebar open? Some other?

**Comment by chrismore** [comment]
@bniolet1 what do you think if we just simply give them the badge if they open the sidebar since most people don't need to click the app store badges to get mobile? It will be the only sidebar that we give people badges just by opening it, but it is the last sidebar on the utility path and you don't need to click a button to successful convert here since you can pull out your phone.

**Comment by bniolet1** [comment]
In in favor of your idea, @chrismore  for exactly the reason you stated. 

As a side note, though, this means we need to land on a plan for how to handle stickers and if sticker panel activates right away, we have to make sure we make a strong enough mobile badge impression before moving on to sticker stuff.
