### ISSUE TITLE
New tab is not modified

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#253]
New tab should be modified with the header/footer message when:

* Sign up for FxA account
* Navigate away from FxA page
* Close FxA page
* Click "no thanks" at bottom of FxA page

Currently, only the last bullet appears to work and that is probably because it is what we have been testing with.

**Comment by FrancescoSTL** [comment]
This is an issue caused by the preloading of content on about:newtab, triggered by a preference (`browser.newtab.preload`) in https://dxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#1721. 

Our best bet is to have releng configs set `browser.newtab.preload` to false, and then manually set it after first load using the preferences/service sdk. @chrismore this will need to be noted to NThomas in our bugzilla bug.

**Comment by fabiorios** [comment]
The header isn't showing up for me either on the first session, as cmore described. Strangely, if I close and reopen Firefox, the first time I load a newtab, the message appears. 

![1](https://cloud.githubusercontent.com/assets/19597198/16630972/765d1a8e-4371-11e6-9b12-6cb4381eaf75.JPG)

**Comment by FrancescoSTL** [comment]
@fabiorios Very strange. I'm fairly certain is has to do with caching. Something else to note in this issue is that the aboutNewtab pagemod is never destroyed, which it should be, in order to prevent the mod from ever happening again (which you currently can get it to do if you hit ctrl-shift-r at any time on the newtab page).

**Comment by FrancescoSTL** [comment]
Looks like the pagemod is being destroyed whenever the browser is closed. If I reopen, not even a ctrl-shift-r displays the header/footer content. Additionally, I've found that a simple refresh is enough to make the content load properly on the page (ctrl-r). 

I'm not sure exactly what is going on here, as I'm still unable to replicate with JPM, but MattN suggested that it could be an issue with the content load times. I'm submitting a new PR which cleans up some things. Also, I am going to suggest that NThomas creates another build with the `browser.newtab.preload` pref set to false just to check and see if the preloading is truly our issue.

**Comment by FrancescoSTL** [comment]
We've now confirmed that this is a caching issue solved by creating a funnelcake with the `browser.newtab.preload` flag set to false by default. Next step: submit PR to flip it back on:
1. If the user loads newtab
2. If 24 hours have passed since initialization of the addon (as a fail-safe)
