### ISSUE TITLE
Funnelcake(v7) change link on "almost done" accounts sign up page

### ISSUE THREAD

**Issue by fabiorios** [mozilla/all-aboard#269]
@chrismore the "no thanks" link on the accounts page shouldn't open a new tab. Can load in this same tab so that the user doesn't have 3 open tabs upon launch of Firefox?

**Comment by chrismore** [comment]
@fabiorios that's the default experience and there's nothing we can easily do about this in v1.0. The default firefox experience opens up about:home (asked and it isn't a pref to change) and /firstrun/ then redirects to about:home and anything you do on the FxA form opens up a newtab to show you your imported data. It can't use the same tab because the verification message may be there waiting.
