### ISSUE TITLE
Three Notifications Per Sidebar & Speed up first interaction

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#329]
Per https://tree.taiga.io/project/jennyd-firefox-onboarding/task/160, we'd like to give users three notifications per sidebar: "As a new user who has been previously been welcomed by Firefox, I want make sure I see my notifications when it is time to play, so I don't miss my turn to move forward in the game."

The first notification for both sidebars should be 2 hours (1/12th of current). Each subsequent notification should happen on 24 hour intervals. Each sidebar should have 3 notifications

**Comment by schalkneethling** [comment]
@chrismore Couple of questions regarding the 3 notifications per sidebar.

1. The amount of time that should pass between each notification, is that going to be 8 hours? i.e. `waitInterval / 3 = 8`?
2. If on browser startup we reschedule the timer, and the amount of time that has passed since the last notification is say 7 hours and 10 minutes or 7 hours and 50 minutes, do we simply reschedule for a hour from now or, do we want to be exact, i.e. actually restart the timer for 50/10 minute from now?
3. Once we have shown the user 3 notifications, and the user has not interacted with the sidebar, do we give up and wait for the destroy timer to "uninstall" the add-on?

**Comment by chrismore** [comment]
@schalkneethling 

1) No, each is going to be 24 hours. Same interval, but re-start the time 2 more times if the first interval has passed without engagement with the CTA.

2) Hmmm. Both of those seem similar logic. Is your question regarding how exact it has to be? 

3) yes, that's the idea. There's the first notification for any sidebar, there's 2 more chances (notifications) to engage with it, If no engagement, wait for the destroy timer to uninstall the add-on.

**Comment by schalkneethling** [comment]
"No, each is going to be 24 hours. Same interval, but re-start the time 2 more times if the first interval has passed without engagement with the CTA."

Ah ok so, if 24 hours has passed but the user has not interacted with the sidebar, notify again for the same sidebar. We do this three times in total i.e. the initial notification and then 2 more.

If no interaction after this time, we give up and let the destroy timer uninstall the add-on.

**Comment by fabiorios** [comment]
^ that's correct @schalkneethling

**Comment by chrismore** [comment]
@schalkneethling like @fabiorios said, yes. 👍
