### ISSUE TITLE
Snippets not progressing with the content number

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#384]
Regardless of what content number you are on, snippets are always at content 1.

**Comment by schalkneethling** [comment]
Improved by https://github.com/mozilla/all-aboard/pull/389 - I am going to have a look at further improving this but, in all honesty, I doubt that there are very many use cases where a user will indefinitely keep about:home open and never close the browser or refresh the page for the entire duration of the on-boarding experience.

So perhaps it is not worth spending to much time on it. Thoughts?

**Comment by chrismore** [comment]
This looks to only be an issue with the Utility track. The values track is advancing. 

Array problem?

**Comment by schalkneethling** [comment]
"This looks to only be an issue with the Utility track. The values track is advancing.
Array problem?"

@chrismore It is pretty hard to see whether the utility track's snippets progress because all 5 steps have the exact same copy, icon, and button so, the only way to know, is to click the button and check that the appropriate sidebar opens.
