### ISSUE TITLE
Remove FxA parameter

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/all-aboard#476]
We need to remove the FxA parameters added to the sign-in/sing-up form that triggers the email journey,

**Comment by schalkneethling** [comment]
Resolved by: https://github.com/mozilla/all-aboard/pull/479

**Comment by chrismore** [comment]
@bniolet1 @schalkneethling why was this additional characters on the utm_campaign fxa url removed from 1.6?

**Comment by chrismore** [comment]
@schalkneethling even though we are not doing email in 1.6, the parameters were nice because the FxA team could segment out the cohorts and determine if onboarding was helping with multi device. Given that there are no parameter changes in 1.6, it means the FxA team can't see them any different. If we wanted to add this back, we would only have one modification to the utm_campaign parameter and that would be appending -onboarding16 to the existing string. It would not trigger anything, but the FxA team could segment their numbers.

**Comment by JennyDouglas** [comment]
@schalkneethling @chrismore We will only add this back into the code if there are other bugs to fix in this current funnelcake, if everything else runs smooth, then we are going out the door as is. This is not a blocker for release.

**Comment by chrismore** [comment]
agree. not blocker. we can create a v1.6.X version and pull it into a future funnelcake if 1.6 is successful.
